/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webapp;

public class App {
    public void start() throws Exception {
        new JettyServer().start();
    }

    public static void main(String[] args) throws Exception {
        new App().start();
    }
}
